[build]
  publish = "."
  command = ""
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
